### ISSUE TITLE
Modified Tutorial

### ISSUE THREAD

**Issue by aiemassfiria** [Huawei-LTE-routers-mods/huawei_balong_modfw_kitchen#1]
Hi @ValdikSS 

Thanks for tools.
I try to modified E5573cs_UPDATE_21.333.64.01.1456_WEBUI_17.100.20.03.306_MRE5

What i do..
1. balong_flash -e E5573cs_UPDATE_21.333.64.01.1456_WEBUI_17.100.20.03.306_MRE5.bin in orig_fw
2. mkdir system in orig_fw and cpio -ivm -F ../08-00590000-System.bin
3. run ./build.sh v7r11 e5573cs_zong_21.333.64.01.1456 orig_fw
4. i get the modified system.cpio in workdir
5. using qhuaweiflash im replacing the system.cpio
6 . i try to flash the modified compiled fw but stop at system flash. means 2 other bin app and webui didnt successfully flash.

its that correct my step?

**Comment by ValdikSS** [comment]
That is correct.
The firmware does not flash due to digital signature mismatch. You either need to flash via boot point + usbloader or resign your firmware as in https://github.com/Huawei-LTE-routers-mods/README/blob/master/how_to_flash_balong_v7r11_without_datalock_code.md

**Comment by ValdikSS** [comment]
Please also pay extra attention on this firmware: **it will unrecoverably lock your global non-locked device**. This firmware is for devices locked to Pakistani Zong Bolt only. It also won't unlock the device, only add modifications.
If you have a hacked-up firmware with SIM unlock for Zong Bolt, it will lock the device.
If you have lower firmware version on Zong Bolt (21.328 for example), you won't be able to downgrade anymore (21.333 firmware writes anti-downgrade bit to the efuse).

**Comment by saqie1393** [comment]
after extract frimmware how to do ? after copy.sh  file not  in directroy please step guide after extract frimware  
Model E5577Cs-321
Frimmware:21.333.01.00.00

**Comment by saqie1393** [comment]
https://androidhost.ru/7v5

i am try on this frimmware...

**Comment by aiemassfiria** [comment]
> Please also pay extra attention on this firmware: **it will unrecoverably lock your global non-locked device**. This firmware is for devices locked to Pakistani Zong Bolt only. It also won't unlock the device, only add modifications.
> If you have a hacked-up firmware with SIM unlock for Zong Bolt, it will lock the device.
> If you have lower firmware version on Zong Bolt (21.328 for example), you won't be able to downgrade anymore (21.333 firmware writes anti-downgrade bit to the efuse).

I see.. I think this modification can unlock the device. right now as i know this model didnt have usbloader... if u have the usbloader for this device please send to my email anacron@outlook.com

**Comment by hassansagar78** [comment]
done it what a smart work by author...is it possible to remove card lock in the fw 21.333.01.1456 zong 5573?

**Comment by aiemassfiria** [comment]
> done it what a smart work by author...is it possible to remove card lock in the fw 21.333.01.1456 zong 5573?

also as the same question...

**Comment by saqie1393** [comment]
> done it what a smart work by author...is it possible to remove card lock in the fw 21.333.01.1456 zong 5573?

Bro any method to e5577cs-321  i am stuck on after extract frimware not know what i do ... base and device overlay folder? please some help..

**Comment by saqie1393** [comment]
https://imgur.com/Lgk2S8q.png

**Comment by aiemassfiria** [comment]
> > done it what a smart work by author...is it possible to remove card lock in the fw 21.333.01.1456 zong 5573?
> 
> Bro any method to e5577cs-321 i am stuck on after extract frimware not know what i do ... base and device overlay folder? please some help..

u should read @ValdikSS warning.. this kitchen its for E5577Bs only....for oled hijack u need to find
*g_current_page,*g_current_Info_page & *g_led_status in binary oled. if hard to find u can use E5577Bs binary oled and use oled_hijack.so compiled by @ValdikSS [https://github.com/Huawei-LTE-routers-mods/huawei_balong_modfw_kitchen/blob/master/device_overlay/e5577s_Bs_tishknet_21.327.62.01.1365/root/app/bin/oled_hijack/oled_hijack.so](url). rename the original oled to oled.orig and use E5372 script. Make sure your permission is 755. Its very hard to understand if u didnt know what to do.

**Comment by saqie1393** [comment]
> > > done it what a smart work by author...is it possible to remove card lock in the fw 21.333.01.1456 zong 5573?
> > 
> > Bro any method to e5577cs-321 i am stuck on after extract frimware not know what i do ... base and device overlay folder? please some help..
> 
> u should read @ValdikSS warning.. this kitchen its for E5577Bs only....for oled hijack u need to find
> *g_current_page,*g_current_Info_page & *g_led_status in binary oled. if hard to find u can use E5577Bs binary oled and use oled_hijack.so compiled by @ValdikSS [https://github.com/Huawei-LTE-routers-mods/huawei_balong_modfw_kitchen/blob/master/device_overlay/e5577s_Bs_tishknet_21.327.62.01.1365/root/app/bin/oled_hijack/oled_hijack.so](url). rename the original oled to oled.orig and use E5372 script. Make sure your permission is 755. Its very hard to understand if u didnt know what to do.
> 

Thanks for information 
kindly suggest which command to system.cpio file replace  in qhuaweiflash

**Comment by ValdikSS** [comment]
@saqie1393 
> after extract frimmware how to do ?

Unpack system partition to system/, app to app/, webui to webui/, if needed.
You'd better read build.sh script, it's only several lines long.

To everyone: please do not turn projects' issues into chat. Your discussion about usbloaders and simunlock has nothing to do with this project.

**Comment by aiemassfiria** [comment]
@ValdikSS can u put openvpn for E5577-321 in this git..is latest fw supported for openvpn? firmware version 21.333..
or we can just use entware tu install the openvpn..thanks..

**Comment by ValdikSS** [comment]
@aiemassfiria openvpn is already present in all base platform images.

**Comment by aiemassfiria** [comment]
Im already try openvpn but error dev tun/tap not found..device is E5577-321

**Comment by pkmani** [comment]
How to get .ko file for unlock e8372h-153 21.333

**Comment by pkmani** [comment]
huawei-e5573 login: admin
login: /etc/passwd: bad record
what will be the password of telnet after successful firmware modification. ?

**Comment by aiemassfiria** [comment]
root:changemerightnow

**Comment by pkmani** [comment]
huawei-e5573 login: root:changemerightnow
login: /etc/passwd: bad record
Password:

not working

**Comment by aiemassfiria** [comment]
i dont have problem with valdik kitchen. check your modification. follow my guide at 1st comment.

**Comment by SpaceCadetSkywalker** [comment]
Is it possible to use this tool with original fw that one can dump from a device? If so, I presume that there must be a way to dump all partitions from such device. How to dump images from e8372h-153 (21.210.03.01.1080 or 21.333.03.00.00) using gnu/linux? Do I have to get telnet access somehow first?

**Comment by iArkAt9** [comment]
hi @ValdikSS

thanks for this best tool
create custome fw complete but while flash error in APP and system flashed succes and modem go flash mode ,and if remove app partition flash succes without error but still syltuck at flash mode.

**Comment by MatMii** [comment]
Hi, does this modification can bypass hotpot data?

**Comment by Awarageo** [comment]
Hello, i wonder how to re-sign a firmware, I've read your tutorial but it's can't understand where to execute "sign" program?
