### ISSUE TITLE
Huawei B310s-927

### ISSUE THREAD

**Issue by saqi755** [Huawei-LTE-routers-mods/huawei_balong_modfw_kitchen#11]
Please can make this file unlocked for all networks [Need Networks Unlocked file B310S-927](https://drive.google.com/file/d/130eX-LJ0fsecEk2ydQ9VDPAOMcOpi116/view?usp=drivesdk)

**Comment by ValdikSS** [comment]
Yes, most probably. However, this is irrelevant to this repository.

**Comment by saqi755** [comment]
Okay but can you do this for us please
