### ISSUE TITLE
Huawei E8372h-155

### ISSUE THREAD

**Issue by debritde** [Huawei-LTE-routers-mods/huawei_balong_modfw_kitchen#14]
Hello, i want to flash the E8372h-155 Model to get the VPN Function.
The problem is i cant find any firmware file online.
Do you have any solution or maybe even a prepared firmware file? :)

**Comment by ValdikSS** [comment]
There are plenty: ftp://serv.valdikss.org.ru/Downloads/Huawei_Firmware/E8372h/
