### ISSUE TITLE
Possible

### ISSUE THREAD

**Issue by saqie1393** [Huawei-LTE-routers-mods/huawei_balong_modfw_kitchen#3]
Kindly add more device overlay like E5577Cs-321  etc because BS model not work oled on this?

**Comment by ValdikSS** [comment]
I don't have this device. You could create it yourself or send me the device using postal services and pay for my job at the rate of $20/hour.

**Comment by saqie1393** [comment]
obfs-local new addtion in kichten..
which purpose of use this and how to work in modem ??

**Comment by ValdikSS** [comment]
This is [simple-obfs](https://github.com/shadowsocks/simple-obfs) client.
Please don't use Github issues for low-effort questions. This could have been easily found by `obfs-local` name.

**Comment by saqie1393** [comment]
Connecting to 192.168.8.1 port 23, please wait...


huawei-device login: root
Password: 


    Run `passwd` command to change telnet password.

    Use `ttl [VALUE]` to set outbound/inbound TTL. Example:
      ttl 64          ttl 0     
    Run `imei [VALUE]` to change IMEI. Example:
      imei 12345678901234

    Execute `anticensorship [VALUE]` to enable
    local transparent censorship circumvention
    proxy and DNS redirection.

    `dns_over_tls` is for DNS over TLS and
    advertisement blocking.
    `adblock_update` to update adblock lists.

    Execute `ipv6` to enable or disable IPv6 support

    `entware` is for Entware software repository.

~ # ttl
/system/bin/ttl [VALUE]
TTL mangling: 64
~ # anticensorship
/system/bin/anticensorship [0 or 1]
Anticensorship status: enabled
WARNING! Anticensorship works only for IPv4 and disables IPv6 DNS queries from the device!
~ # anticensorship 1
~ # adblock
-ash: adblock: not found
~ # dns_over_tls
/system/bin/dns_over_tls 0 - disable DNS over TLS
/system/bin/dns_over_tls 1 - enable DNS over TLS
/system/bin/dns_over_tls 2 - enable DNS over TLS with adblock
Cloudflare and Google servers are used by default.
Check DNS over TLS configuration in /etc/stubby/stubby.yml
DNS over TLS status: enabled + adblock
WARNING! DNS over TLS disables IPv6 DNS queries from the device!
~ # obfs-local

simple-obfs 0.0.5

  maintained by Max Lv 

  usage:

    obfs-local

       -s            Host name or IP address of your remote server.
       -p            Port number of your remote server.
       -l             Port number of your local server.
       --obfs           Enable obfuscating: HTTP or TLS (Experimental).
       --http-method      HTTP request method for obfuscating (Experimental).
       --obfs-host     Hostname for obfuscating (Experimental).
       --obfs-uri       HTTP path uri for obfuscating (Experimental).

       [-a ]                Run as another user.
       [-f ]            The file path to store pid.
       [-t ]             Socket timeout in seconds.
       [-c ]         The path to config file.
       [-n ]              Max number of open files.
       [-b ]       Local address to bind.


       [--fast-open]              Enable TCP fast open.
                                  with Linux kernel > 3.7.0.
       [--mptcp]                  Enable Multipath TCP on MPTCP Kernel.

       [-v]                       Verbose mode.
       [-h, --help]               Print this message.

~ # obfs-local -h

simple-obfs 0.0.5

  maintained by Max Lv 

  usage:

    obfs-local

       -s            Host name or IP address of your remote server.
       -p            Port number of your remote server.
       -l             Port number of your local server.
       --obfs           Enable obfuscating: HTTP or TLS (Experimental).
       --http-method      HTTP request method for obfuscating (Experimental).
       --obfs-host     Hostname for obfuscating (Experimental).
       --obfs-uri       HTTP path uri for obfuscating (Experimental).

       [-a ]                Run as another user.
       [-f ]            The file path to store pid.
       [-t ]             Socket timeout in seconds.
       [-c ]         The path to config file.
       [-n ]              Max number of open files.
       [-b ]       Local address to bind.


       [--fast-open]              Enable TCP fast open.
                                  with Linux kernel > 3.7.0.
       [--mptcp]                  Enable Multipath TCP on MPTCP Kernel.

       [-v]                       Verbose mode.
       [-h, --help]               Print this message.

~ # obfs
-ash: obfs: not found
~ # obfs-local --obfs
 2020-06-16 03:45:36 [simple-obfs] ERROR: Unrecognized option: (null)

simple-obfs 0.0.5

  maintained by Max Lv 

  usage:

    obfs-local

       -s            Host name or IP address of your remote server.
       -p            Port number of your remote server.
       -l             Port number of your local server.
       --obfs           Enable obfuscating: HTTP or TLS (Experimental).
       --http-method      HTTP request method for obfuscating (Experimental).
       --obfs-host     Hostname for obfuscating (Experimental).
       --obfs-uri       HTTP path uri for obfuscating (Experimental).

       [-a ]                Run as another user.
       [-f ]            The file path to store pid.
       [-t ]             Socket timeout in seconds.
       [-c ]         The path to config file.
       [-n ]              Max number of open files.
       [-b ]       Local address to bind.


       [--fast-open]              Enable TCP fast open.
                                  with Linux kernel > 3.7.0.
       [--mptcp]                  Enable Multipath TCP on MPTCP Kernel.

       [-v]                       Verbose mode.
       [-h, --help]               Print this message.

~ # obfs-local -s server_ip -p 8139 -l 1984 --obfs http --obfs-host www.bing.com

-ash: obfs-local -s server_ip -p 8139 -l 1984 --obfs http --obfs-host www.bing.com: not found
~ # ?ss-local -c config.json --plugin obfs-local --plugin-opts ?"?obfs=http;obfs

-host=www.bing.com?"
-ash: ​ss-local -c config.json --plugin obfs-local --plugin-opts ​​obfs=http;obfs-host=www.bing.com​: not found
~ # ?ss-local -c config.json --plugin obfs-local --plugin-opts ??obfs=http;obfs-

host=www.bing.com
-ash: ​ss-local -c config.json --plugin obfs-local --plugin-opts ​​obfs=http: not found
-ash: obfs-host=www.bing.com: not found
~ # ?ss-server -c config.json --plugin obfs-server --plugin-opts ?"?obfs=http?"
-ash: ​ss-server -c config.json --plugin obfs-server --plugin-opts ​​obfs=http​: not found
~ # obfs-local -c
how to config and start in modem where config file?

~ # obfs-local --help

simple-obfs 0.0.5

  maintained by Max Lv 

  usage:

    obfs-local

       -s            Host name or IP address of your remote server.
       -p            Port number of your remote server.
       -l             Port number of your local server.
       --obfs           Enable obfuscating: HTTP or TLS (Experimental).
       --http-method      HTTP request method for obfuscating (Experimental).
       --obfs-host     Hostname for obfuscating (Experimental).
       --obfs-uri       HTTP path uri for obfuscating (Experimental).

       [-a ]                Run as another user.
       [-f ]            The file path to store pid.
       [-t ]             Socket timeout in seconds.
       [-c ]         The path to config file.
       [-n ]              Max number of open files.
       [-b ]       Local address to bind.


       [--fast-open]              Enable TCP fast open.
                                  with Linux kernel > 3.7.0.
       [--mptcp]                  Enable Multipath TCP on MPTCP Kernel.

       [-v]                       Verbose mode.
       [-h, --help]               Print this message.

~ #

**Comment by saqie1393** [comment]
How to config and start in the modem where config file?

~ # obfs-local --help

simple-obfs 0.0.5

  maintained by Max Lv 

  usage:

    obfs-local

       -s            Host name or IP address of your remote server.
       -p            Port number of your remote server.
       -l             Port number of your local server.
       --obfs           Enable obfuscating: HTTP or TLS (Experimental).
       --http-method      HTTP request method for obfuscating (Experimental).
       --obfs-host     Hostname for obfuscating (Experimental).
       --obfs-uri       HTTP path uri for obfuscating (Experimental).

       [-a ]                Run as another user.
       [-f ]            The file path to store pid.
       [-t ]             Socket timeout in seconds.
       [-c ]         The path to config file.
       [-n ]              Max number of open files.
       [-b ]       Local address to bind.


       [--fast-open]              Enable TCP fast open.
                                  with Linux kernel > 3.7.0.
       [--mptcp]                  Enable Multipath TCP on MPTCP Kernel.

       [-v]                       Verbose mode.
       [-h, --help]               Print this message.

~ #
