### ISSUE TITLE
iptables.orig

### ISSUE THREAD

**Issue by severkyt** [Huawei-LTE-routers-mods/huawei_balong_modfw_kitchen#4]
<img src="https://i.ibb.co/gZLjhXQ/github.jpg" alt="github" border="0">
1. extract firmware to workdir
2. create system folder in workdir
execute script
i'm try using e8372 script and got cpio file in workdir but not for v7r2 base

**Comment by saqie1393** [comment]
http://4pda.ru/forum/index.php?showtopic=625406&view=findpost&p=95230972

already post this model frimware

**Comment by ValdikSS** [comment]
I suppose you did not unpack system partition into orig_fw/system.
