### ISSUE TITLE
TTL fix

### ISSUE THREAD

**Issue by aiemassfiria** [Huawei-LTE-routers-mods/huawei_balong_modfw_kitchen#7]
Some network have issue with TTL fix.

For example: In firmware 21.333.63.00.1217 E5577-321

Telco cannot bypass with error no internet connection. 

Try to replace the ttlfix and ttlfix.sh with insmod kpatch.ko also cannot solve the problem.

**Comment by ValdikSS** [comment]
I guess you're using some third-party unlocking module, which also patch the kernel in an unexpected way. Not this project issue.
